# Generated by Django 3.0.5 on 2020-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200515_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbank',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Blog Title'),
        ),
    ]
