# Generated by Django 3.0.5 on 2020-05-14 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Recruiter name')),
                ('designation', models.CharField(max_length=25, null=True, verbose_name='Recruiters designation')),
                ('starts', models.DateField(null=True, verbose_name='Interview Date')),
                ('ends', models.DateField(null=True, verbose_name='Interview Ends Date')),
                ('company', models.CharField(max_length=50, verbose_name='Company Name')),
                ('image', models.ImageField(upload_to='media', verbose_name='Profile Pic')),
                ('industry', models.CharField(choices=[('Accounting Jobs', 'Accounting Jobs'), ('Interior Design Jobs', 'Interior Design Jobs'), ('Bank Jobs Content', 'Bank Jobs Content'), ('Writing Jobs', 'Writing Jobs'), ('Consultant Jobs', 'Consultant Jobs'), ('Engineering Jobs', 'Engineering Jobs'), ('Export Import Jobs', 'Export Import Jobs'), ('Merchandiser Jobs', 'Merchandiser Jobs'), ('Security Jobs', 'Security Jobs'), ('HR Jobs', 'HR Jobs'), ('Hotel Jobs', 'Hotel Jobs'), ('Ecommerce Jobs', 'Ecommerce Jobs'), ('Mobile Jobs', 'Mobile Jobs'), ('Network administrator Jobs', 'Network administrator Jobs'), ('IT Jobs', 'IT Jobs'), ('BPO Jobs', 'BPO Jobs'), ('Legal Jobs', 'Legal Jobs'), ('Marketing Jobs', 'Marketing Jobs'), ('Packaging Jobs', 'Packaging Jobs'), ('Pharma Jobs', 'Pharma Jobs'), ('Maintenance Jobs', 'Maintenance Jobs'), ('Logistics Jobs', 'Logistics Jobs'), ('Sales Jobs', 'Sales Jobs'), ('Secretary Jobs', 'Secretary Jobs'), ('Film Jobs', 'Film Jobs'), ('Teacher Jobs', 'Teacher Jobs'), ('Graphic Designer Jobs', 'Graphic Designer Jobs'), ('Other', 'Other')], max_length=50, verbose_name='Type of Industry')),
                ('location', models.CharField(max_length=100, verbose_name='Job Location')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('job_details', models.CharField(max_length=200, null=True, verbose_name='Job Description')),
                ('job_exp', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('Fresher', 'Fresher'), ('Any', 'Any')], max_length=50, verbose_name='Required experience in years')),
                ('skill', models.CharField(max_length=100, null=True, verbose_name='Required Skills')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted')),
                ('contact', models.IntegerField(null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email id')),
                ('author', models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
