# Generated by Django 3.0.5 on 2020-04-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databank',
            name='price',
        ),
    ]
