# Generated by Django 3.0.5 on 2020-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_databank_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name=' Your Location'),
        ),
    ]
