# Generated by Django 3.0.5 on 2020-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200423_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databank',
            name='address',
        ),
        migrations.AddField(
            model_name='databank',
            name='contact',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Phone Number (Your phone number will show up on your Ad.)'),
        ),
        migrations.AddField(
            model_name='databank',
            name='email',
            field=models.EmailField(max_length=20, null=True, verbose_name='Email (Your email address will not be shared with others.)'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Price (Be specific with currency sign first then amount)'),
        ),
    ]
