# Generated by Django 3.0.5 on 2020-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200423_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='category',
            field=models.CharField(choices=[('01', 'Buy & Sell'), ('02', 'Cars & Vehicles'), ('03', 'Real Estate'), ('04', 'Mobiles'), ('05', 'Furniture'), ('06', 'Bikes'), ('07', 'Jobs'), ('08', 'Services'), ('09', 'Community'), ('10', 'Vacation Rentals')], default='01', max_length=20, null=True, verbose_name='Select a category'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='content',
            field=models.TextField(max_length=400, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email (Your email address will not be shared with others.)'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Price (Be specific with currency type & amount)'),
        ),
    ]
