# Generated by Django 3.0.5 on 2020-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200423_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='category',
            field=models.CharField(choices=[('Buy & Sell', 'Buy & Sell'), ('Cars & Vehicles', 'Cars & Vehicles'), ('Real Estate', 'Real Estate'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Services', 'Services'), ('Community', 'Community'), ('Vacation Rentals', 'Vacation Rentals')], default='01', max_length=20, null=True, verbose_name='Select a category'),
        ),
    ]
