# Generated by Django 3.0.5 on 2020-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200424_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='owner',
            field=models.CharField(max_length=17, null=True, verbose_name='Name of the owner'),
        ),
    ]
