# Generated by Django 3.0.3 on 2020-04-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='friends',
            name='discription',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='friends',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
