# Generated by Django 3.0.5 on 2020-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_album_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
