# Generated by Django 3.0.5 on 2020-04-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_musician_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='artist',
        ),
    ]
