# Generated by Django 3.0.5 on 2020-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_remove_musician_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='play',
            field=models.ManyToManyField(to='friends.Musician'),
        ),
    ]
