# Generated by Django 3.0.5 on 2020-04-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_auto_20200412_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
