# Generated by Django 3.0.5 on 2020-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_auto_20200422_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('M', 'Straight Male'), ('GM', 'Gay Male'), ('GM', 'Bi Male'), ('SF', 'Straight Female'), ('GF', 'Gay Female'), ('BF', 'Bi Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='age',
            field=models.CharField(choices=[('junior', '18-20'), ('senior', '20-30'), ('young', '30-40'), ('adult', '40-60')], max_length=10, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='discription',
            field=models.TextField(max_length=100, null=True, verbose_name='Interested to'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='photo',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='About Me'),
        ),
    ]
