# Generated by Django 3.0.5 on 2020-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_auto_20200422_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='language',
            field=models.CharField(default='English', max_length=50, null=True, verbose_name='Languages | Speak'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='age',
            field=models.CharField(choices=[('junior', 'till-20'), ('senior', '20-30'), ('young', '30-40'), ('adult', '40-60')], max_length=10, null=True, verbose_name='Age (Must be over 18 years old)'),
        ),
    ]
