# Generated by Django 3.0.5 on 2020-04-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20200422_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='body',
            field=models.CharField(choices=[('01', 'Choose one'), ('02', 'Athletic/Muscular'), ('03', 'Slim/Slender'), ('04', 'Average'), ('05', 'A little above average'), ('06', 'Full Figured')], default='01', max_length=20, null=True, verbose_name='Body Type'),
        ),
        migrations.AddField(
            model_name='friends',
            name='height',
            field=models.CharField(choices=[('01', 'Choose one'), ('02', 'Very Short'), ('03', 'Short'), ('04', 'Average'), ('05', 'Above Average'), ('06', 'Tall')], default='01', max_length=20, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='age',
            field=models.CharField(choices=[('junior', 'till-20'), ('senior', '20-24'), ('young', '25-34'), ('adult', '35-44'), ('forty', '45-54'), ('fifty', '55-64'), ('sixty', '65 or older'), ('secret', 'I prefer to keep secret')], default='young', max_length=10, null=True, verbose_name='What is your age?'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='language',
            field=models.CharField(default='English, ', max_length=50, null=True, verbose_name='Languages | Speak'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='title',
            field=models.CharField(default='The best thing about me is ', max_length=100, null=True, verbose_name='About Me'),
        ),
    ]
