# Generated by Django 3.0.5 on 2020-04-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_auto_20200422_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='fees',
            field=models.CharField(choices=[('01', 'negotiable'), ('02', '$10 hour'), ('03', '$20 hour'), ('04', '$30 hour'), ('05', '$40 hour'), ('06', '$50+ hour')], default='01', max_length=50, null=True, verbose_name='My fees'),
        ),
    ]
