# Generated by Django 3.0.5 on 2020-04-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0012_friends_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='title',
            field=models.TextField(default='The best thing about me is ', max_length=100, null=True, verbose_name='A short description about yourself'),
        ),
    ]
