# Generated by Django 3.0.5 on 2020-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0013_auto_20200422_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='activites',
            field=models.BooleanField(choices=[('01', 'negotiable'), ('02', '$10 hour'), ('03', '$20 hour'), ('04', '$30 hour'), ('05', '$40 hour'), ('06', '$50+ hour')], max_length=10, null=True, verbose_name='Activities'),
        ),
    ]
