# Generated by Django 3.0.5 on 2020-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_databank_address'),
        ('friends', '0014_friends_activites'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='address',
            field=models.ManyToManyField(to='application.databank'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='activites',
            field=models.CharField(default='I am Up For ', max_length=10, null=True, verbose_name='Available for, Business Events, Parties, Yoga, Movies, Music, Hanging Out, Religious, Swimming, Workout Partner etc or I am Up For Everything'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='discription',
            field=models.CharField(max_length=100, null=True, verbose_name='Interested to'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='photo',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Profile Picture, '),
        ),
    ]
