# Generated by Django 3.0.5 on 2020-04-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0015_auto_20200423_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='activites',
            new_name='activities',
        ),
    ]
