# Generated by Django 3.0.5 on 2020-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0016_auto_20200423_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='address',
        ),
        migrations.AddField(
            model_name='friends',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Your Location'),
        ),
    ]
