# Generated by Django 3.0.5 on 2020-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0017_auto_20200423_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='title',
        ),
        migrations.AddField(
            model_name='friends',
            name='about',
            field=models.CharField(default='The best thing about me is ', max_length=100, null=True, verbose_name='A short description about yourself'),
        ),
    ]
