# Generated by Django 3.0.5 on 2020-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0018_auto_20200423_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='about',
            field=models.CharField(default='The best thing about me is ', max_length=200, null=True, verbose_name='A short description about yourself'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='activities',
            field=models.CharField(default='I am Up For ', max_length=20, null=True, verbose_name='Available for, Business Events, Parties, Yoga, Movies, Music, Hanging Out, Religious, Swimming, Workout Partner etc or I am Up For Everything'),
        ),
    ]
