# Generated by Django 3.0.5 on 2020-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0019_auto_20200423_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='activities',
            field=models.CharField(default='I am Up For ', max_length=200, null=True, verbose_name='Available for, Business Events, Parties, Yoga, Movies, Music, Hanging Out, Religious, Swimming, Workout Partner etc or I am Up For Everything'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='language',
            field=models.CharField(default='English, ', max_length=100, null=True, verbose_name='Languages | Speak'),
        ),
    ]
