# Generated by Django 3.0.5 on 2020-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0022_auto_20200423_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='age',
            field=models.CharField(choices=[('till-20', 'till-20'), ('20-24', '20-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65 or older', '65 or older'), ('I prefer to keep secret', 'I prefer to keep secret')], default='young', max_length=100, null=True, verbose_name='What is your age?'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='body',
            field=models.CharField(choices=[('Choose one', 'Choose one'), ('Athletic/Muscular', 'Athletic/Muscular'), ('Slim/Slender', 'Slim/Slender'), ('Average', 'Average'), ('A little above average', 'A little above average'), ('Full Figured', 'Full Figured')], default='01', max_length=200, null=True, verbose_name='Body Type'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='fees',
            field=models.CharField(choices=[('negotiable', 'negotiable'), ('$10 hour', '$10 hour'), ('$20 hour', '$20 hour'), ('$30 hour', '$30 hour'), ('$40 hour', '$40 hour'), ('$50+ hour', '$50+ hour')], default='01', max_length=50, null=True, verbose_name='My fees'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Straight Male', 'Straight Male'), ('Gay Male', 'Gay Male'), ('Bi Male', 'Bi Male'), ('Straight Female', 'Straight Female'), ('Gay Female', 'Gay Female'), ('Bi Female', 'Bi Female')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='height',
            field=models.CharField(choices=[('Choose one', 'Choose one'), ('Very Short', 'Very Short'), ('Short', 'Short'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Tall', 'Tall')], default='01', max_length=50, null=True, verbose_name='Height'),
        ),
    ]
