# Generated by Django 3.0.5 on 2020-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0024_auto_20200424_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='Gender'),
        ),
    ]
