# Generated by Django 3.0.5 on 2020-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0025_auto_20200429_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True, verbose_name='Gender'),
        ),
    ]
