# Generated by Django 3.0.5 on 2020-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0026_auto_20200430_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='photo',
            field=models.FileField(null=True, upload_to='media', verbose_name='Profile Picture,'),
        ),
    ]
