# Generated by Django 3.0.5 on 2020-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0028_auto_20200508_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='file',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Profile Picture,'),
        ),
    ]
