# Generated by Django 3.0.5 on 2020-05-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0031_auto_20200508_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='media', verbose_name='Profile Picture,')),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='file',
        ),
        migrations.DeleteModel(
            name='newfriends',
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='friends.friends'),
        ),
    ]
