# Generated by Django 3.0.5 on 2020-05-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0033_auto_20200508_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='about',
            field=models.TextField(default='The best thing about me is ', max_length=400, null=True, verbose_name='A short description about yourself'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
