# Generated by Django 3.0.5 on 2020-05-11 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0034_auto_20200509_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='activities',
            field=models.CharField(default='I am up for ', max_length=200, null=True, verbose_name='Available for, Business Events, Parties, Yoga, Movies, Music, Hanging Out, Religious, Swimming, Workout Partner etc or I am Up For Everything'),
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friends'),
        ),
    ]
