# Generated by Django 3.0.5 on 2020-05-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0036_auto_20200510_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Profile Picture,'),
        ),
    ]
