# Generated by Django 3.0.5 on 2020-05-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0037_friends_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='image',
            new_name='photo',
        ),
    ]
