# Generated by Django 3.0.5 on 2020-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('starts', models.DateTimeField(verbose_name='Starts')),
                ('ends', models.DateTimeField(verbose_name='Ends')),
                ('image', models.ImageField(upload_to='media', verbose_name='Event Image')),
                ('description', models.CharField(max_length=200, verbose_name='Event Description')),
                ('name', models.CharField(max_length=40, verbose_name='Organiser Name')),
                ('description2', models.CharField(max_length=100, verbose_name='Organiser Description')),
                ('tickets', models.CharField(max_length=50, verbose_name='Tickets')),
                ('types', models.CharField(max_length=40, verbose_name='Event Type')),
            ],
        ),
    ]
