# Generated by Django 3.0.5 on 2020-04-17 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200417_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted'),
        ),
    ]
