# Generated by Django 3.0.5 on 2020-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='contact',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='events',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email id'),
        ),
        migrations.AddField(
            model_name='events',
            name='topic',
            field=models.CharField(choices=[('01', 'Select a topic'), ('02', 'Auto, Boat & Air'), ('03', 'Business & Professional'), ('04', 'Charities & Causes'), ('05', 'Community & Culture'), ('06', 'Family & Education'), ('07', 'Fashion & Beauty'), ('08', 'Film, Media & Entertainment'), ('09', 'Food & Drink'), ('10', 'Government & Politics'), ('11', 'Health & Wellness'), ('12', 'Hobbies & Special Interests'), ('13', 'Home & Lifestyle'), ('14', 'Music'), ('15', 'Other'), ('16', 'Performing & Visual Arts'), ('17', 'Religion & Spirituality'), ('18', 'School Activities'), ('19', 'Science & Technology'), ('20', 'Seasonal'), ('21', 'Sports & Fitness'), ('22', 'Travel & Outdoor')], max_length=50, null=True, verbose_name='Event Topic'),
        ),
        migrations.AlterField(
            model_name='events',
            name='ends',
            field=models.CharField(max_length=200, null=True, verbose_name='Event date & time, Ends'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='events',
            name='starts',
            field=models.CharField(max_length=200, null=True, verbose_name='Event date & time, Starts'),
        ),
    ]
