# Generated by Django 3.0.5 on 2020-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200423_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='topic',
            field=models.CharField(choices=[('Select a topic', 'Select a topic'), ('Auto, Boat & Air', 'Auto, Boat & Air'), ('03', 'Business & Professional'), ('04', 'Charities & Causes'), ('05', 'Community & Culture'), ('06', 'Family & Education'), ('07', 'Fashion & Beauty'), ('08', 'Film, Media & Entertainment'), ('09', 'Food & Drink'), ('10', 'Government & Politics'), ('11', 'Health & Wellness'), ('12', 'Hobbies & Special Interests'), ('13', 'Home & Lifestyle'), ('Music', 'Music'), ('15', 'Other'), ('16', 'Performing & Visual Arts'), ('17', 'Religion & Spirituality'), ('18', 'School Activities'), ('19', 'Science & Technology'), ('20', 'Seasonal'), ('21', 'Sports & Fitness'), ('22', 'Travel & Outdoor')], default='01', max_length=50, null=True, verbose_name='Event Topic'),
        ),
        migrations.AlterField(
            model_name='events',
            name='types',
            field=models.CharField(choices=[('01', 'Select the type of event'), ('02', 'Appearance or Signing'), ('03', 'Attraction'), ('04', 'Camp, Trip or Retreat'), ('05', 'Concert or Performance'), ('06', 'Conference'), ('07', 'Course, Training or Workshop'), ('08', 'Dinner or Gala'), ('09', 'Festival or Fair'), ('10', 'Meeting or Networking Event'), ('11', 'Party or Social Gathering'), ('12', 'Race or Endurance Event'), ('13', 'Tournament'), ('14', 'Rally'), ('15', 'Seminar or Talk'), ('16', 'Tour'), ('17', 'Tradeshow, Consumer Show..')], default='01', max_length=50, null=True, verbose_name='Event Type'),
        ),
    ]
