# Generated by Django 3.0.5 on 2020-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200424_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='topic',
            field=models.CharField(choices=[('Select a topic', 'Select a topic'), ('Auto, Boat & Air', 'Auto, Boat & Air'), ('Business & Professional', 'Business & Professional'), ('Charities & Causes', 'Charities & Causes'), ('Community & Culture', 'Community & Culture'), ('Family & Education', 'Family & Education'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Film, Media & Entertainment', 'Film, Media & Entertainment'), ('Food & Drink', 'Food & Drink'), ('Government & Politics', 'Government & Politics'), ('Health & Wellness', 'Health & Wellness'), ('Hobbies & Special Interests', 'Hobbies & Special Interests'), ('Home & Lifestyle', 'Home & Lifestyle'), ('Music', 'Music'), ('Other', 'Other'), ('Performing & Visual Arts', 'Performing & Visual Arts'), ('Religion & Spirituality', 'Religion & Spirituality'), ('School Activities', 'School Activities'), ('Science & Technology', 'Science & Technology'), ('Seasonal', 'Seasonal'), ('Sports & Fitness', 'Sports & Fitness'), ('Travel & Outdoor', 'Travel & Outdoor')], default='01', max_length=50, null=True, verbose_name='Event Topic'),
        ),
        migrations.AlterField(
            model_name='events',
            name='types',
            field=models.CharField(choices=[('Select the type of event', 'Select the type of event'), ('Appearance or Signing', 'Appearance or Signing'), ('Attraction', 'Attraction'), ('Camp, Trip or Retreat', 'Camp, Trip or Retreat'), ('Concert or Performance', 'Concert or Performance'), ('Conference', 'Conference'), ('Course, Training or Workshop', 'Course, Training or Workshop'), ('Dinner or Gala', 'Dinner or Gala'), ('Festival or Fair', 'Festival or Fair'), ('Meeting or Networking Event', 'Meeting or Networking Event'), ('Party or Social Gathering', 'Party or Social Gathering'), ('Race or Endurance Event', 'Race or Endurance Event'), ('Tournament', 'Tournament'), ('Rally', 'Rally'), ('Seminar or Talk', 'Seminar or Talk'), ('Tour', 'Tour'), ('Tradeshow, Consumer Show..', 'Tradeshow, Consumer Show..')], default='01', max_length=50, null=True, verbose_name='Event Type'),
        ),
    ]
