# Generated by Django 3.0.5 on 2020-05-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200424_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Event Description'),
        ),
    ]
